Repository 100-hours-a-week/3-team-CareerBee-be, pull requests merged in 2025-05, with the labels that each got.

#66 👷 Ci: CI/CD 파이프라인 - Initial
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: optimization

#67 👷 Ci: yml 수정
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: optimization

#71 👷 Ci: CI/CD 성공 여부 알림 설정
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: optimization

#72 👷 Ci: Job 이름 수정
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: optimization

#74 🧱 Infra: Run time Error 알림 시스템 구축
  build.gradle
  src/main/java/org/choon/careerbee/common/exception/CustomExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: optimization

#75 👷 Ci: Sentry 인증 토큰 환경변수로 추가
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: optimization

#80 Develop
  .github/ISSUE_TEMPLATE/pr-template.md
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  build.gradle
  src/main/java/org/choon/careerbee/common/exception/CustomExceptionHandler.java
  src/main/java/org/choon/careerbee/domain/auth/controller/AuthController.java
  src/main/java/org/choon/careerbee/domain/auth/service/auth/AuthServiceImpl.java
  src/main/java/org/choon/careerbee/domain/company/controller/CompanyController.java
  src/main/java/org/choon/careerbee/domain/company/controller/WishCompanyController.java
  src/main/java/org/choon/careerbee/domain/company/service/CompanyCommandServiceImpl.java
  src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryService.java
  src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryServiceImpl.java
  src/main/java/org/choon/careerbee/domain/member/service/MemberQueryService.java
  src/main/java/org/choon/careerbee/domain/member/service/MemberQueryServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: optimization

#113 👷 Ci: 정적 코드 분석 절차 추가
  .github/workflows/lint.yml
  build.gradle
  config/checkstyle/google_checks.xml
  config/pmd/pmd-ruleset.xml
Labels: Test

#95 Test/94
  src/main/java/org/choon/careerbee/common/enums/CustomResponseStatus.java
  src/main/java/org/choon/careerbee/common/exception/CustomExceptionHandler.java
  src/main/resources/application-test.yml
  src/test/java/org/choon/careerbee/domain/company/controller/CompanyControllerTest.java
  src/test/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepositoryImplTest.java
  src/test/java/org/choon/careerbee/domain/company/service/CompanyQueryServiceImplTest.java
  src/test/java/org/choon/careerbee/fixture/CompanyFixture.java
  src/test/java/org/choon/careerbee/fixture/MemberFixture.java
  src/test/java/org/choon/careerbee/fixture/WishCompanyFixture.java
Labels: Test

#126 Test/125 : 토큰 재발급 기능에 대한 테스트코드 작성
  src/main/java/org/choon/careerbee/common/exception/CustomExceptionHandler.java
  src/main/java/org/choon/careerbee/util/jwt/JwtUtil.java
  src/test/java/org/choon/careerbee/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/choon/careerbee/domain/auth/service/auth/AuthServiceImplTest.java
Labels: Test

#129 🧱 Infra: Spring Actuator
  build.gradle
  src/main/java/org/choon/careerbee/config/security/SecurityConfig.java
  src/main/java/org/choon/careerbee/filter/jwt/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 제안

#154 Feat/133 : 대회 입장 기능 개발
  src/main/java/org/choon/careerbee/common/enums/CustomResponseStatus.java
  src/main/java/org/choon/careerbee/domain/competition/controller/CompetitionController.java
  src/main/java/org/choon/careerbee/domain/competition/domain/Competition.java
  src/main/java/org/choon/careerbee/domain/competition/domain/CompetitionParticipant.java
  src/main/java/org/choon/careerbee/domain/competition/repository/CompetitionParticipantRepository.java
  src/main/java/org/choon/careerbee/domain/competition/service/CompetitionCommandService.java
  src/main/java/org/choon/careerbee/domain/competition/service/CompetitionCommandServiceImpl.java
  src/test/java/org/choon/careerbee/domain/competition/controller/CompetitionControllerTest.java
  src/test/java/org/choon/careerbee/domain/competition/repository/CompetitionRepositoryTest.java
  src/test/java/org/choon/careerbee/domain/competition/service/CompetitionCommandServiceImplTest.java
  src/test/java/org/choon/careerbee/fixture/CompetitionFixture.java
Labels: Test, Feat, PR
